version: '3.8'

services:
  book-rental-postgres:
    container_name: book-rental-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - book-rental-postgres-volume:/var/lib/postgresql/data

volumes:
  book-rental-postgres-volume: